City-of-Helsinki/events-helsinki-monorepo

README.md
apps/hobbies-helsinki/README.md
docs/about-lint-staged.md
docs/docker/docker.md
docs/howto/how-to.md
packages/common-i18n/README.md
packages/components/README.md
packages/eslint-config-bases/README.md

Updates to documentation by replacing the example content with some actual examples
HH-213 HH-221.

docs: replaced examples with actual hobbies-helsinki content

---

.github/workflows/ci-events-helsinki-staging.yml
.github/workflows/ci-hobbies-helsinki-review.yml
.github/workflows/ci-hobbies-helsinki-staging.yml

staging testing

---

azure-pipelines-harrastukset-ci-staging.yml

Add harrastukset  devops staging pipeline

harrastukset devops staging pipeline

---

azure-pipelines-tapahtumat-release.yml
azure-pipelines-tapahtumat-test.yml

Azure DevOps pipelines for tapahtumat release and test deployments
**[DEVOPS-465](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-465):**

build: azure devops pipelines for tapahtumat release and test DEVOPS-465

---

azure-pipelines-harrastukset-federation-router-test.yml

**[DEVOPS-468](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-468): Harrastukset federation router**

build: harrastukset federation router pipeline

---

azure-pipelines-liikunta-federation-router-release.yml
azure-pipelines-liikunta-federation-router-review.yml
azure-pipelines-liikunta-federation-router-test.yml
azure-pipelines-liikunta-review.yml
azure-pipelines-tapahtumat-federation-router-release.yml
azure-pipelines-tapahtumat-federation-router-review.yml
azure-pipelines-tapahtumat-federation-router-test.yml
azure-pipelines-tapahtumat-review.yml

Add missing platta pipelines
**[DEV-455](https://helsinkisolutionoffice.atlassian.net/browse/DEV-455): Review pipeline**
**[DEV-468](https://helsinkisolutionoffice.atlassian.net/browse/DEV-468): Liikunta and federation routers to Platta **

build: router and review pipelines for tapahtumat and liikunta

---

apps/events-helsinki/k6LoadTests.js
azure-pipelines-harrastukset-federation-router-review.yml
azure-pipelines-liikunta-federation-router-review.yml
azure-pipelines-tapahtumat-federation-router-review.yml

tapahtumat k6 loadtest url

---

apps/events-helsinki/src/common-events/utils/headless-cms/headlessCmsUtils.tsx
apps/hobbies-helsinki/src/common-events/utils/headless-cms/headlessCmsUtils.tsx
apps/sports-helsinki/src/common-events/utils/headless-cms/headlessCmsUtils.tsx

**[HCRC-78](https://helsinkisolutionoffice.atlassian.net/browse/HCRC-78): As a content manager I can add a show all -link in the carousel**

feat: use CMS provided carousel show all URLs

---

packages/components/src/components/mapBox/MapBox.tsx

chore: change the order of the map links in the MabBox -component

---

proxies/events-graphql-proxy/nodemon.json
proxies/events-graphql-proxy/package.json
proxies/events-graphql-proxy/src/index.ts
proxies/events-graphql-proxy/src/schema/event/resolvers.ts
proxies/events-graphql-proxy/src/schema/keyword/resolvers.ts
proxies/events-graphql-proxy/src/schema/neighborhood/resolvers.ts
proxies/events-graphql-proxy/src/schema/organization/resolvers.ts
proxies/events-graphql-proxy/src/schema/place/resolvers.ts
proxies/events-graphql-proxy/src/schema/resolvers.ts
proxies/events-graphql-proxy/src/types.ts
proxies/events-graphql-proxy/tsconfig.json
proxies/events-graphql-proxy/yarn.lock
yarn.lock

The server did not start before these changes:
- The @types/cors was missing
- Change the Tsconfiguration because
"SyntaxError: Cannot use import statement outside a module" was raised.
- Resolvers were wrongly typed for buildSubgraphSchema-command.
- After changing the resolvers return type, the any-types were needed.

build: fix the build time issues

---

.release-please-manifest.json
azure-pipelines-events-graphql-proxy-release.yml
azure-pipelines-events-graphql-proxy-review.yml
azure-pipelines-events-graphql-proxy-test.yml
azure-pipelines-venue-graphql-proxy-release.yml
azure-pipelines-venue-graphql-proxy-review.yml
azure-pipelines-venue-graphql-proxy-test.yml
proxies/venue-graphql-proxy/package.json

Pipeline files. The platta repo for proxies is created here: https://dev.azure.com/City-of-Helsinki/liikunta/_git/graphql-proxy-pipelines

Liikunta-374: add pipelines for events and venue graphql proxy

---

apps/events-helsinki/package.json
apps/events-helsinki/src/common-events/utils/headless-cms/headlessCmsUtils.tsx
apps/events-helsinki/src/constants.ts
apps/events-helsinki/src/domain/venue/constants.ts
apps/events-helsinki/src/domain/venue/utils/getVenueSourceId.ts
apps/events-helsinki/src/domain/venue/venueDetails/VenueDetails.tsx
apps/events-helsinki/src/domain/venue/venueDetails/venueDetails.module.scss
apps/events-helsinki/src/hooks/useRHHCConfig.tsx
apps/hobbies-helsinki/package.json
apps/hobbies-helsinki/src/common-events/utils/headless-cms/headlessCmsUtils.tsx
apps/hobbies-helsinki/src/constants.ts
apps/hobbies-helsinki/src/domain/venue/constants.ts
apps/hobbies-helsinki/src/domain/venue/utils/getVenueSourceId.ts
apps/hobbies-helsinki/src/domain/venue/venueDetails/VenueDetails.tsx
apps/hobbies-helsinki/src/domain/venue/venueDetails/venueDetails.module.scss
apps/hobbies-helsinki/src/hooks/useRHHCConfig.tsx
apps/sports-helsinki/config/jest/TestProviders.tsx
apps/sports-helsinki/package.json
apps/sports-helsinki/src/common-events/utils/headless-cms/headlessCmsUtils.tsx
apps/sports-helsinki/src/components/domain/graphql/generated/graphql.ts
apps/sports-helsinki/src/domain/nextApi/types.ts
apps/sports-helsinki/src/domain/venue/venueDetails/VenueDetails.tsx
apps/sports-helsinki/src/domain/venue/venueDetails/venueDetails.module.scss
apps/sports-helsinki/src/hooks/useRHHCConfig.tsx
packages/components/codegen.yml
packages/components/package.json
packages/components/src/components/domain/unifiedSearch/unifiedSearchConstants.ts
packages/components/src/types/generated/graphql.tsx
yarn.lock

Support of the sports locations
Updated schemas are not supoorted in events staging, so it will break the staging if merged. LocationsSelected missing from modules in staging and has to be fixed by headless cms team. But it should work with production headless cms

feat: sports locations support

---

azure-pipelines-events-graphql-proxy-release.yml
azure-pipelines-events-graphql-proxy-review.yml
azure-pipelines-events-graphql-proxy-test.yml
azure-pipelines-venue-graphql-proxy-release.yml
azure-pipelines-venue-graphql-proxy-review.yml
azure-pipelines-venue-graphql-proxy-test.yml

fix(liikunta-374): wrong repo name

---

release-please-config.json

Add venue proxy to the release please

---

proxies/events-graphql-proxy/jest.config.js

fix: broken jest config for events graphql proxy

---

README.md

refs LIIKUNTA-426
**[LIIKUNTA-426](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-426)**
[LIIKUNTA-426]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIIKUNTA-426 | docs(README): document use of symbolic links and using them on Windows

---

apps/events-helsinki/src/domain/event/__tests__/EventPageContainer.test.tsx
apps/events-helsinki/src/domain/event/eventKeywords/__tests__/EventKeywords.test.tsx
apps/hobbies-helsinki/src/domain/event/__tests__/EventPageContainer.test.tsx
apps/hobbies-helsinki/src/domain/event/eventKeywords/__tests__/EventKeywords.test.tsx
apps/sports-helsinki/src/domain/event/__tests__/EventPageContainer.test.tsx
apps/sports-helsinki/src/domain/event/eventKeywords/__tests__/EventKeywords.test.tsx
apps/sports-helsinki/src/domain/venue/venueKeywords/__tests__/VenueKeywords.test.tsx
packages/components/src/components/keyword/KeywordTag.tsx
packages/components/src/components/keyword/__tests__/KeywordButton.test.tsx

Reverts City-of-Helsinki/events-helsinki-monorepo#264

Revert "fix: disable keyword onclick"

---

apps/sports-helsinki/src/domain/search/venueSearch/VenueSearch.tsx
packages/common-i18n/src/locales/fi/appSports.json

fix: change example search terms

---

packages/common-i18n/src/locales/en/search.json

fix(sports): fix English translations of search types

---

azure-pipelines-liikunta-release.yml

refs LIIKUNTA-467
**[LIIKUNTA-467](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-467)**
[LIIKUNTA-467]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIIKUNTA-467 | feat(askem): enable Askem in release pipeline i.e. staging & production

---

azure-pipelines-events-graphql-proxy-review.yml
azure-pipelines-venue-graphql-proxy-review.yml

Define proxy build arguments and runtime variables for pipelines

chore: proxy review pipeline arguments

---

packages/components/src/components/domain/venue/query.ts
packages/components/src/types/generated/graphql.tsx
proxies/events-graphql-federation/subgraphs/venues/venues.graphql
proxies/events-graphql-federation/supergraph.graphql
proxies/venue-graphql-proxy/src/types/types.ts

This is groundwork for PR #448 
refs LIIKUNTA-522 (needs this change to function)
**[LIIKUNTA-522](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-522)**
[LIIKUNTA-522]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update venue-graphql-proxy related types and supergraph

---

packages/common-i18n/src/locales/fi/appSports.json
packages/common-i18n/src/locales/sv/appSports.json

refs LIIKUNTA-556
**[LIIKUNTA-556](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-556)**
[LIIKUNTA-556]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIIKUNTA-556 | feat(sports): change appName to "Helsinki Liikkuu" / "Idrott och motion"

---

apps/events-helsinki/package.json
apps/hobbies-helsinki/package.json
apps/sports-helsinki/package.json
packages/components/package.json
yarn.lock

refs LIIKUNTA-466
**[LIIKUNTA-466](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-466)**
https://github.com/City-of-Helsinki/react-helsinki-headless-cms/pull/125
See page:
- https://liikunta-pr500.dev.hel.ninja/fi/pages/testisivu-tyyleja-varten
[LIIKUNTA-466]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIIKUNTA-466 | fix: fix table styles by using HCRC v1.0.0-alpha217

---

apps/events-helsinki/package.json
apps/hobbies-helsinki/package.json
apps/sports-helsinki/package.json
packages/components/package.json
yarn.lock

Related HCRC pull request:
https://github.com/City-of-Helsinki/react-helsinki-headless-cms/pull/127
refs LIIKUNTA-466
**[LIIKUNTA-466](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-466)**
[LIIKUNTA-466]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIIKUNTA-466 | fix: fix HDS table paddings by using HCRC v1.0.0-alpha218

---

apps/sports-helsinki/src/domain/search/combinedSearch/adapters/__tests__/EventSearchAdapter.test.ts
apps/sports-helsinki/src/domain/search/eventSearch/constants.tsx

refs LIIKUNTA-344
**[LIIKUNTA-344](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-344)**
[LIIKUNTA-344]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIIKUNTA-344 | feat(sports): update events/hobby search related target group keywords

---

apps/events-helsinki/package.json
apps/events-helsinki/src/common-events/components/category/__tests__/__snapshots__/CategoryFilter.test.tsx.snap
apps/hobbies-helsinki/package.json
apps/hobbies-helsinki/src/common-events/components/category/__tests__/__snapshots__/CategoryFilter.test.tsx.snap
apps/sports-helsinki/package.json
apps/sports-helsinki/src/common-events/components/category/__tests__/__snapshots__/CategoryFilter.test.tsx.snap
apps/sports-helsinki/src/domain/venue/venueInfo/VenueInfo.tsx
apps/sports-helsinki/src/domain/venue/venueInfo/venueInfo.module.scss
packages/components/package.json
packages/components/src/components/domain/event/eventInfo/EventInfo.tsx
packages/components/src/components/eventHero/__tests__/EventHero.test.tsx
packages/components/src/components/keyword/__tests__/__snapshots__/KeywordButton.test.tsx.snap
yarn.lock

This PR is an ALTERNATIVE for PR #592
- email links use "mailto:" prefix and envelope icon
- phone links use "tel:" prefix and phone icon
also:
- use react-helsinki-headless-cms v1.0.0-alpha246
- this makes `<Link>` components with "mailto:" prefixed hrefs be
rendered as email links i.e. with an envelope icon everywhere
- this makes `<Link>` components with "tel:" prefixed hrefs be
rendered as phone links i.e. with a phone icon everywhere
refs LIIKUNTA-445
[LIIKUNTA-445](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-445)
URL: https://harrastukset.hel.fi/fi/kurssit/helsinki:aggiclcl5e
URL: https://harrastukset-pr597.dev.hel.ninja/fi/kurssit/helsinki:aggiclcl5e
URL: https://liikunta.hel.fi/fi/paikat/tprek:430
URL: https://liikunta-pr597.dev.hel.ninja/fi/paikat/tprek:430
URL: …

LIIKUNTA-445 | feat: add phone & email links with icons to event & venue detail page

---

Dockerfile

**BUILDER_FROM_IMAGE** in Platta **pipelines**:
- [liikunta-ui-build-config.yml](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=%2Fdevops%2Fliikunta-ui-build-config.yml&_a=contents&version=GBmaster) sets BUILDER_FROM_IMAGE build arg to:
- `container-registry.platta-net.hel.fi/hki-kuva-liikunta/${LIIKUNTA_CACHE_IMAGE}:latest`
- LIIKUNTA_CACHE_IMAGE is set to:
- `liikunta-cache-test` in [testing](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=%2Fvariables%2Fliikunta-variables-testing.yml&_a=contents&version=GBmaster) environment
- `liikunta-cache-test` in [review](https://dev.azure.com/City-of-Helsinki/liikunta/_git/liikunta-pipelines?path=/variables/liikunta-variables-development.yml&_a=contents&version=GBmaster) environments
- …

LIIKUNTA-623 | fix(dockerfile): put "ARG BUILDER_FROM_IMAGE" back in Dockerfile

---

Dockerfile
DockerfileCache
proxies/events-graphql-federation/Dockerfile
proxy.Dockerfile

Revert UBI dockerfile changes
- [LIIKUNTA-623](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-623) (Testing whether caused by the UBI dockerfile changes)
[LIIKUNTA-623]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert UBI dockerfile changes

---

apps/sports-helsinki/redirectCampaignRoutes.config.js

fix: add new redirect for ulkokuntosaliohjaukset

---

README.md
apps/events-helsinki/README.md
apps/hobbies-helsinki/README.md
apps/sports-helsinki/README.md
proxies/events-graphql-federation/subgraphs/events/README.md

TH-1422 TH-1340.
Documentation for main event search and similar events search.
Also, added "Matomo" to "DigiaIiris" text, to deascribe that it's actually Matomo service and improvements to service map documentation.

docs(apps): event search parameters
