- Dockerfile
- apps/hobbies-helsinki/package.json
Mount type bind or cache are not supported on current version (4.10.35) of OpenShift build
[PLAENH-202](https://helsinkisolutionoffice.atlassian.net/browse/PLAENH-202)
> Oc build failure

- apps/events-helsinki/config/jest/mocks/eventListMocks.ts
- apps/events-helsinki/src/domain/footer/FooterCategories.tsx
- apps/events-helsinki/src/domain/search/eventSearch/__tests__/Search.test.tsx
- apps/events-helsinki/src/domain/search/eventSearch/__tests__/utils.test.ts
- apps/events-helsinki/src/domain/search/eventSearch/constants.tsx
- apps/events-helsinki/src/domain/search/eventSearch/filterSummary/FilterSummary.tsx
- apps/events-helsinki/src/domain/search/eventSearch/types.ts
- apps/events-helsinki/src/domain/search/eventSearch/utils.tsx
- apps/events-helsinki/src/domain/search/landingPageSearch/LandingPageSearch.tsx
- packages/common-i18n/src/locales/en/home.json
- packages/common-i18n/src/locales/fi/home.json
- packages/common-i18n/src/locales/sv/home.json
- [refactor(events-helsinki): rename course to event in *categories](https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/56/commits/a09b6b37a4ca74c42f1515855d354071c34a5d51) 
- [feat(events-helsinki): update event categories to production values](https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/56/commits/b2d057e9581b903a551f2aacaf7dce80cefd6e0a) 
- [refactor(events-helsinki): remove unused categories/keywords/filters](https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/56/commits/eb5ba66fe635dd58ba182229f253cf5b7e515536) 
- [refactor(events-helsinki): add const assertions, reduce code duplication](https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/56/commits/59621d4d93cd0319721de284638941dd00107bce) …
> TH-1256 & TH-1276 | Update search categories to production values

- apps/events-helsinki/src/domain/search/eventSearch/AdvancedSearch.tsx
- apps/events-helsinki/src/domain/search/eventSearch/EventSearchPageContainer.tsx
- apps/events-helsinki/src/domain/search/eventSearch/__tests__/Search.test.tsx
- apps/events-helsinki/src/domain/search/landingPageSearch/LandingPageSearchForm.tsx
- apps/events-helsinki/src/pages/search/index.tsx
- apps/hobbies-helsinki/src/domain/search/eventSearch/AdvancedSearch.tsx
- apps/hobbies-helsinki/src/domain/search/eventSearch/EventSearchPageContainer.tsx
- apps/hobbies-helsinki/src/domain/search/landingPageSearch/LandingPageSearchForm.tsx
- apps/hobbies-helsinki/src/pages/search/index.tsx
- apps/sports-helsinki/src/domain/footer/Footer.tsx
- apps/sports-helsinki/src/domain/footer/FooterCategories.tsx
- apps/sports-helsinki/src/domain/search/eventSearch/AdvancedSearch.tsx
- apps/sports-helsinki/src/domain/search/eventSearch/EventSearchPageContainer.tsx
- apps/sports-helsinki/src/domain/search/landingPageSearch/LandingPageSearchForm.tsx
- apps/sports-helsinki/src/domain/search/venueSearch/VenueSearch.tsx
- apps/sports-helsinki/src/pages/search/index.tsx
- packages/common-i18n/src/locales/en/appEvents.json
- packages/common-i18n/src/locales/en/appHobbies.json
- packages/common-i18n/src/locales/en/appSports.json
- packages/common-i18n/src/locales/en/search.json
- packages/common-i18n/src/locales/fi/appEvents.json
- packages/common-i18n/src/locales/fi/appHobbies.json
- packages/common-i18n/src/locales/fi/appSports.json
- packages/common-i18n/src/locales/fi/search.json
- packages/common-i18n/src/locales/sv/appEvents.json
- packages/common-i18n/src/locales/sv/appHobbies.json
- packages/common-i18n/src/locales/sv/appSports.json
- packages/common-tests/browser-tests/page-model/landingPage.ts
Changed a couple of search-related translation texts of events and hobbies, and also reorganized the translations a bit to make the structure more logical and easier to reason about. There is still room for improvement in that area.
**[TH-1273](https://helsinkisolutionoffice.atlassian.net/browse/TH-1273): Create Events and Hobbies specific translations in the monorepo**
**[TH-1275](https://helsinkisolutionoffice.atlassian.net/browse/TH-1275): Change site headings**
> TH-1273 & TH-1275 | Fix search related translations

- apps/events-helsinki/src/domain/search/eventSearch/AdvancedSearch.tsx
- apps/events-helsinki/src/domain/search/eventSearch/constants.tsx
- apps/events-helsinki/src/domain/search/eventSearch/utils.tsx
- apps/events-helsinki/src/domain/search/landingPageSearch/LandingPageSearch.tsx
Removed "influence" and "food" categories from the landing page search shortcuts, and applied a custom ordering for the shortcuts that is the same for all the languages. In contrast, The advanced search page category filter still has all the categories sorted alphabetically as before.
**[TH-1285](https://helsinkisolutionoffice.atlassian.net/browse/TH-1285)**
> Tune landing page category search shortcuts

- apps/events-helsinki/browser-tests/roles/allCookiesUser.ts
- apps/events-helsinki/browser-tests/search-page/search-page.testcafe.ts
- apps/events-helsinki/src/common-events/utils/headless-cms/headlessCmsUtils.tsx
- apps/events-helsinki/src/pages/pages/[...slug].tsx
- apps/hobbies-helsinki/browser-tests/roles/allCookiesUser.ts
- apps/hobbies-helsinki/browser-tests/search-page/search-page.testcafe.ts
- apps/hobbies-helsinki/src/common-events/utils/headless-cms/headlessCmsUtils.tsx
- apps/hobbies-helsinki/src/pages/pages/[...slug].tsx
- apps/sports-helsinki/src/common-events/utils/headless-cms/headlessCmsUtils.tsx
- apps/sports-helsinki/src/pages/pages/[...slug].tsx
- packages/common-tests/browser-tests/page-model/consent-modal.ts
- packages/common-tests/browser-tests/page-model/eventSearchPage.ts
- packages/common-tests/browser-tests/page-model/index.ts
HH-255. This PR was originally to handle the dynamic pages root-path so that it would always be translated, but I couldn't find a reasonable way to implement such a feature this time. However, these were done while investigating and planning the (self) requested feature:
1. add browser test base for a search page
2. Fix the dynamic pages get static path
The pages were generated wrongly on build time - the path was not right!
> Fix the dynamic pages get static path

- apps/events-helsinki/src/pages/_document.tsx
- apps/hobbies-helsinki/src/pages/_document.tsx
- apps/sports-helsinki/src/pages/_document.tsx
- packages/components/src/components/document/Document.tsx
- packages/components/src/components/index.ts
This fixes the issue where a huge HKI logo flashes briefly when a user navigates to the site. The implementation is pretty much directly copy-pasted from [linkedregistrations-ui](https://github.com/City-of-Helsinki/linkedregistrations-ui/blob/7542320c8e2df6349799a1404fecca4a809519ae/src/pages/_document.tsx).
**[HH-276](https://helsinkisolutionoffice.atlassian.net/browse/HH-276): Helsinki logo flashes full page size in the beginning of a page load**
> feat: enable HDS server side rendering support

- apps/events-helsinki/src/domain/app/AppConfig.ts
- apps/hobbies-helsinki/src/domain/app/AppConfig.ts
- apps/sports-helsinki/src/domain/app/AppConfig.ts
**[LIIKUNTA-361](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-361): Links doesn't work when using Headless CMS Pages module**
> Fix page link URLs

- apps/events-helsinki/src/domain/event/eventInfo/__tests__/OtherEventTimes.test.tsx
- apps/events-helsinki/src/domain/event/queryUtils.ts
- apps/events-helsinki/src/domain/search/eventSearch/SearchPage.tsx
- apps/events-helsinki/src/domain/search/eventSearch/__tests__/EventSearchPageContainer.test.tsx
- apps/hobbies-helsinki/src/domain/event/eventInfo/__tests__/OtherEventTimes.test.tsx
- apps/hobbies-helsinki/src/domain/event/queryUtils.ts
- apps/hobbies-helsinki/src/domain/search/eventSearch/SearchPage.tsx
- apps/hobbies-helsinki/src/domain/search/eventSearch/__tests__/EventSearchPageContainer.test.tsx
- apps/sports-helsinki/src/domain/event/eventInfo/__tests__/OtherEventTimes.test.tsx
- apps/sports-helsinki/src/domain/event/queryUtils.ts
- apps/sports-helsinki/src/domain/search/eventSearch/SearchPage.tsx
- apps/sports-helsinki/src/domain/search/eventSearch/__tests__/EventSearchPageContainer.test.tsx
- apps/sports-helsinki/src/domain/search/venueSearch/SearchPage.tsx
- packages/common-i18n/src/locales/fi/event.json
- packages/common-i18n/src/locales/fi/search.json
refs LIIKUNTA-355 (noticed the typo while working on this ticket)
**[LIIKUNTA-355](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-355)**
[LIIKUNTA-355]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: rename typoed errorLoadMode to errorLoadMore

- packages/common-i18n/src/locales/en/search.json
- packages/common-i18n/src/locales/fi/search.json
- packages/common-i18n/src/locales/sv/search.json
Practically `"Show more hobbies (<count>)"` -> `"Show more (<count>)`.
**[TH-1289](https://helsinkisolutionoffice.atlassian.net/browse/TH-1289)**
[TH-1289]: https://helsinkisolutionoffice.atlassian.net/browse/TH-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TH-1289 | fix(th-1289): make buttonLoadMore text unrelated to hobbies i.e. generic

- apps/events-helsinki/.env.local.example
- apps/events-helsinki/.env.test
- apps/hobbies-helsinki/.env.local.example
- apps/hobbies-helsinki/.env.test
- apps/sports-helsinki/.env.local.example
- apps/sports-helsinki/.env.test
- proxies/events-graphql-federation/README.md
The ".kuva." containing URLs have been removed from use.
`-`
> fix: remove .kuva from events-graphql-federation-*.test.kuva.hel.ninja

- packages/graphql-proxy-server/src/server.ts
I got the 200 OK now:
```
codelicious@Jaakkos-MBP sports-helsinki % curl -v http://localhost:4100/api/readiness                                                                                           git events-helsinki-monorepo/apps/sports-helsinki main 
*   Trying 127.0.0.1:4100...
* Connected to localhost (127.0.0.1) port 4100 (#0)
> GET /api/readiness HTTP/1.1
> Host: localhost:4100
> User-Agent: curl/7.86.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: text/html; charset=utf-8
< Content-Length: 2
< ETag: W/"2-nOO9QiTIwXgNtWtBJezz8kv3SLc"
< Date: Fri, 27 Jan 2023 08:30:30 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host localhost left intact
OK% …
```
> fix(liikunta-374): fix readiness and healthz routes

- apps/sports-helsinki/src/domain/search/combinedSearch/SearchUtilities.tsx
- apps/sports-helsinki/src/domain/search/eventSearch/searchResultList/eventsOrderBySelect.module.scss
- apps/sports-helsinki/src/domain/search/eventSearch/searchResultList/unifiedSearchOrderBySelect.module.scss
- apps/sports-helsinki/src/domain/search/venueSearch/VenueSearch.tsx
refs LIIKUNTA-355 (UI fixes related to unified search)
refs LIIKUNTA-356 (UI fixes related to linked events search)
**[LIIKUNTA-355](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-355)**
**[LIIKUNTA-356](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-356)**
`-`
[LIIKUNTA-355]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIIKUNTA-356]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-356 | fix: use 2rem margin under order by selects & black "Show on map" button

- apps/sports-helsinki/src/domain/search/eventSearch/constants.tsx
**[LIIKUNTA-341](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-341)**
`-`
[LIIKUNTA-341]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-341 | docs(sports): list names of SPORTS_COURSES_KEYWORDS in addition to IDs

- apps/events-helsinki/src/domain/event/eventInfo/OrganizationInfo.tsx
- apps/events-helsinki/src/domain/event/eventInfo/__tests__/EventInfo.test.tsx
- apps/hobbies-helsinki/src/domain/event/eventInfo/OrganizationInfo.tsx
- apps/sports-helsinki/src/domain/event/eventInfo/OrganizationInfo.tsx
- apps/sports-helsinki/src/domain/event/eventInfo/__tests__/EventInfo.test.tsx
- apps/sports-helsinki/src/domain/search/combinedSearch/utils.ts
- packages/common-i18n/src/locales/en/event.json
- packages/common-i18n/src/locales/fi/event.json
- packages/common-i18n/src/locales/sv/event.json
- packages/components/src/types/event-types.ts
Filtering venues by publisher does not work because no publisher
information is currently available in the venue data to the best of my
current knowledge.
refs LIIKUNTA-412
Now links back to the search page using URL parameter:
- `searchType=General` for events
- `searchType=Course` for hobbies
The label of the link is also now changed based on whether it points
back to events or hobbies.
Add tests for the publisher link label and URL.
refs LIIKUNTA-412
**[LIIKUNTA-412](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-412)**
- ![sports-hobby](https://user-images.githubusercontent.com/77663720/222413853-02f964c1-64bc-443f-87b4-c4ae350f16a2.png)
- ![hobby-fi](https://user-images.githubusercontent.com/77663720/222413336-7e15d429-3817-4ceb-b5d3-792b14e267f0.png)
- …
> LIIKUNTA-412 | feat(sports): make "Show other events/hobbies by publisher" link on event detail page work

- apps/events-helsinki/i18nRoutes.config.js
- apps/events-helsinki/next.config.js
- apps/events-helsinki/redirectRoutes.config.js
- apps/events-helsinki/src/__tests__/redirectRoutes.test.tsx
- apps/hobbies-helsinki/i18nRoutes.config.js
- apps/sports-helsinki/i18nRoutes.config.js
Rewrite URLs in order to support previous version URLs:
- /fi/home -> /fi
- /sv/home -> /sv
- /en/home -> /en
- /fi/events -> /fi/haku
- /sv/events -> /sv/sok
- /en/events -> /en/search
refs TH-1302
The /accessibility and /about rewrite routes are unnecessary as the
pages are available at:
- accessibility page:
- /fi/sivut/saavutettavuusseloste
- /en/pages/accessibility-statement
- /sv/sidor/tillganglighetsutlatande
- about page:
- /fi/sivut/tietoa-palvelusta
- /en/pages/about
- /sv/sidor/om-tjansten
refs TH-1302
TH-1302
**[TH-1302](https://helsinkisolutionoffice.atlassian.net/browse/TH-1302)**
[TH-1302]: https://helsinkisolutionoffice.atlassian.net/browse/TH-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TH-1302 | feat(events): support previous version URLs

- .github/workflows/release-please.yml
- README.md
It seems the workflow can’t be triggered on the release event. From documentation
> When you use the repository’s GITHUB_TOKEN to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs.
> chore: release-please workflow trigger from github event do not work

- proxies/events-graphql-federation/subgraphs/unified-search/unified-search.graphql
- proxies/events-graphql-federation/supergraph.graphql
what was done:
```bash
cd ./proxies/events-graphql-federation
rover subgraph introspect \
https://kuva-unified-search.api.test.hel.ninja/search \
> subgraphs/unified-search/unified-search.graphql
npx prettier subgraphs/unified-search/unified-search.graphql -w
rover supergraph compose --config ./supergraph-config.yaml \
> ./supergraph.graphql
```
refs LIIKUNTA-511 (groundwork related to target group filtering)
**[LIIKUNTA-511](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-511)**
[LIIKUNTA-511]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-511 | chore: update unified-seach subgraph and supergraph after that

- proxies/events-graphql-proxy/src/__tests__/eventIntegration.test.ts
- proxies/events-graphql-proxy/src/schema/event/typeDefs.ts
- proxies/events-graphql-proxy/src/schema/event/utils.ts
- proxies/events-graphql-proxy/src/types/types.ts
publisherAncestor is mapped to published_ancestor parameter in Linked
Events event search e.g.
https://api.hel.fi/linkedevents/v1/event/?publisher_ancestor=ahjo%3A00001
for showing city of Helsinki's events
refs LIIKUNTA-510
**[LIIKUNTA-510](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-510)**
https://events-graphql-proxy-pr411.dev.hel.ninja/proxy/graphql
with query
```graphql
query EventList {
eventList(publisherAncestor: "ahjo:u48040030") {
data {
name {
fi
}
provider {
fi
}
}
}
}
```
returned data
```json
{
"data": {
"eventList": {
"data": [
{
"name": {
"fi": "Drag on myös nuorten laji"
},
"provider": {
"fi": "Seta"
}
},
{
"name": {
"fi": "Neonya!! Party - Hardcore Heat"
},
"provider": {
"fi": "Neonya!! Party "
}
},
{
"name": {
"fi": "Nuorten puistoalue Helsinki Pride …
```
> LIIKUNTA-510 | feat(events-graphql-proxy): add publisherAncestor parameter to eventList

- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/CombinedSearchFormAdapter.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/EventSearchAdapter.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/VenueSearchAdapter.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/__tests__/CombinedSearchFormAdapter.test.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/__tests__/EventSearchAdapter.test.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/__tests__/__snapshots__/CombinedSearchProvider.test.tsx.snap
- apps/sports-helsinki/src/domain/search/combinedSearch/constants.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/types.ts
- apps/sports-helsinki/src/domain/search/eventSearch/filterSummary/FilterSummary.tsx
- packages/common-i18n/src/locales/en/common.json
- packages/common-i18n/src/locales/fi/common.json
- packages/common-i18n/src/locales/sv/common.json
- packages/components/src/components/domain/event/eventInfo/__tests__/OtherEventTimes.test.tsx
- packages/components/src/components/domain/eventSearch/query.ts
- packages/components/src/components/domain/unifiedSearch/graphql/unifiedSearchList.query.ts
- packages/components/src/components/domain/unifiedSearch/graphql/unifiedSearchMap.query.ts
- packages/components/src/components/filterButton/types.ts
- packages/components/src/components/filters/HelsinkiOnlyFilter.tsx
- packages/components/src/components/index.ts
- packages/components/src/constants/event-constants.ts
- packages/components/src/types/generated/graphql.tsx
NOTE:
- No UI support yet except through FilterSummary i.e. the tags under the search bar
- `helsinkiOnly=true` **query parameter must be added manually** into the **URL** to test out this functionality
`helsinkiOnly=true` query parameter will filter all searches with city of
Helsinki
refs LIIKUNTA-509, LIIKUNTA-510
**[LIIKUNTA-509](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-509)**
**[LIIKUNTA-510](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-510)**
https://liikunta-pr410.dev.hel.ninja/fi/search?searchType=Venue
https://liikunta-pr410.dev.hel.ninja/fi/search?searchType=Venue&helsinkiOnly=true
[LIIKUNTA-509]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1 …
> LIIKUNTA-509, LIIKUNTA-510 | feat(sports): add "Helsinki only" filter to venue/event/hobby search

- apps/events-helsinki/package.json
- apps/hobbies-helsinki/package.json
- apps/sports-helsinki/package.json
- packages/components/package.json
- yarn.lock
related to PRs:
https://github.com/City-of-Helsinki/events-helsinki-monorepo/pull/413
https://github.com/City-of-Helsinki/react-helsinki-headless-cms/pull/114
> chore: use react-helsinki-headless-cms v1.0.0-alpha188

- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/CombinedSearchFormAdapter.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/__tests__/CombinedSearchFormAdapter.test.ts
NOTE:
- I have no idea why the typoed cleanHelsinkOnly function didn't raise a type error before, I fixed that
make sure CombinedSearchFormAdapter's clean function calls all available
field specific cleaning functions
refs LIIKUNTA-548 (noticed while working on this ticket)
**[LIIKUNTA-548](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-548)**
[LIIKUNTA-548]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-548 | fix(sports): fix CombinedSearchFormAdapter's clean function

- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/__tests__/CombinedSearchFormAdapter.test.ts
- packages/components/src/utils/typescript.utils.ts
- proxies/venue-graphql-proxy/src/types.ts
- proxies/venue-graphql-proxy/src/utils/utils.ts
refs LIIKUNTA-488, LIIKUNTA-548
**[LIIKUNTA-488](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-488)**
**[LIIKUNTA-548](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-548)**
[LIIKUNTA-488]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIIKUNTA-548]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: test clean function uniqueness, simplify venue proxy types

- .release-please-manifest.json
fixes this error:
```
❯ Fetching release-please-config.json from branch main
❯ Fetching .release-please-manifest.json from branch main
release-please release-pr
...
ConfigurationError: base (City-of-Helsinki/events-helsinki-monorepo):
Failed to parse manifest versions JSON: .release-please-manifest.json...
Unexpected string in JSON at position 199
at fetchReleasedVersions (/usr/local/lib/node_modules/release-ple...
at process.processTicksAndRejections (node:internal/process/task_...
at async parseReleasedVersions (/usr/local/lib/node_modules/relea...
at async Promise.all (index 1)
at async Manifest.fromManifest (/usr/local/lib/node_modules/relea...
at async Object.handler (/usr/local/lib/node_modules/release-plea...
releaserName: 'base',
repository: …
```
> chore: fix .release-please-manifest.json by fixing commas

- apps/events-helsinki/README.md
- apps/hobbies-helsinki/README.md
- apps/sports-helsinki/README.md
NOTE: This is a sort of a dummy commit! See the rationale:
- This corrects a word in each apps' README.md files to trigger the release-please action in order to be able to release the Askem enabling from 323f6f546939b0586f9d52438795e0b4da6d1d89 through the normal release process.
refs LIIKUNTA-467
**[LIIKUNTA-467](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-467)**
[LIIKUNTA-467]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-467 | feat(askem): enable Askem in staging & production, fix typos in READMEs

- apps/sports-helsinki/config/jest/mockDataUtils.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/__tests__/CombinedSearchProvider.test.tsx
- apps/sports-helsinki/src/domain/search/eventSearch/filterSummary/FilterSummary.tsx
- apps/sports-helsinki/src/domain/search/eventSearch/filterSummary/__tests__/FilterSummary.test.tsx
- apps/sports-helsinki/src/domain/search/eventSearch/utils.tsx
- packages/components/src/components/filterButton/types.ts
- packages/components/src/components/filters/AgeFilter.tsx
- packages/components/src/components/filters/DateFilter.tsx
- packages/components/src/components/filters/OrganizationFilter.tsx
- packages/components/src/components/index.ts
Summary:
- Changed the publisher filter to an organization filter in sports-helsinki
NOTE:
- `FilterType` could use more refactoring but tried to make the type
overlap with `keyof CombinedSearchAdapterInput` more explicit
refs LIIKUNTA-548
**[LIIKUNTA-548](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-548)**
[LIIKUNTA-548]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-548 | fix(sports): fix removing publisher filter from FilterSummary

- packages/graphql-proxy-server/src/constants.ts
- packages/graphql-proxy-server/src/context/ContextValue.ts
- packages/graphql-proxy-server/src/enums.ts
- packages/graphql-proxy-server/src/error/IgnorableGraphQLError.ts
- packages/graphql-proxy-server/src/index.ts
- packages/graphql-proxy-server/src/server-config/server-config.ts
- packages/graphql-proxy-server/src/server.ts
- packages/graphql-proxy-server/src/types.ts
- proxies/events-graphql-proxy/package.json
- proxies/events-graphql-proxy/src/index.ts
- proxies/events-graphql-proxy/src/schema/event/constants.ts
- proxies/events-graphql-proxy/src/schema/event/resolvers.ts
- proxies/events-graphql-proxy/src/schema/event/utils.ts
- proxies/events-graphql-proxy/tsconfig.json
- proxies/venue-graphql-proxy/package.json
- proxies/venue-graphql-proxy/tsconfig.json
HH-325.
The LinkedEvents has some false structured event objects that we would like to filter out when fetching a list of events, just to make the client more fail tolerant. It should be noted that the actual issues are in the data of the LinkedEvents, but this way the fix can be delivered faster.
A new custom ignorable Graphql-error type was created. The ignorability means that the error throwing can be skipped if the request contains a custom "X-Ignored-Error-Code" header and the error code is set there as a value.
**With this kind of solution, it's not the server that makes the decision that the errors are ignored, but the client!**
----
When the `X-Ignored-Error-Code` header is not set, the EventList query fails with a new code `"UNPOPULATED_MANDATORY_DATA"`. **Note the newly given …
> feat: false structured events can be ignored by using http-headers

- proxies/events-graphql-federation/router.yaml
HH-325
Propagate the new custom headers that the events-graphql-proxy started to support. Otherwise the router won't have those headers when the request is routed from the router to the events subgraph.
> feat(router): propagate all headers to events-proxy

- apps/sports-helsinki/src/domain/app/appConstants.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/CombinedSearchFormAdapter.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/adapters/CombinedSearchProvider.tsx
- apps/sports-helsinki/src/domain/search/combinedSearch/constants.ts
- apps/sports-helsinki/src/domain/search/combinedSearch/types.ts
- apps/sports-helsinki/src/domain/search/eventSearch/filterSummary/FilterSummary.tsx
- packages/components/src/constants/venue-constants.ts
- packages/components/src/utils/typescript.utils.ts
This works by removing all the backward compatible input fields as well
as the currently used input fields from the URL search parameters.
also:
- add type safety to CombinedSearchFormAdapter's input handling with
use of getSingleValueInput and getMultiValueInput functions
- use "as const" with initialCombinedSearchFormValues but still ensure
it is compatible with CombinedSearchAdapterInput with the use of
satisfies operator, likewise for the other initial search adapter
values
refs LIIKUNTA-554
**[LIIKUNTA-554](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-554)**
Tested locally that clearing all filters works if used `publisher` or `places` URL search parameter.
[LIIKUNTA-554]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
> LIIKUNTA-554 | fix(sports): fix clearing filter summary i.e. filters under search bar

- apps/events-helsinki/src/domain/app/AppConfig.ts
- apps/events-helsinki/src/domain/app/__tests__/AppConfig.test.tsx
- apps/events-helsinki/src/pages/_app.tsx
- apps/events-helsinki/src/pages/cookie-consent/index.tsx
- apps/hobbies-helsinki/src/domain/app/AppConfig.ts
- apps/hobbies-helsinki/src/domain/app/__tests__/AppConfig.test.tsx
- apps/hobbies-helsinki/src/pages/_app.tsx
- apps/hobbies-helsinki/src/pages/cookie-consent/index.tsx
- apps/sports-helsinki/src/domain/app/AppConfig.ts
- apps/sports-helsinki/src/domain/app/__tests__/AppConfig.test.tsx
- apps/sports-helsinki/src/pages/_app.tsx
- apps/sports-helsinki/src/pages/cookie-consent/index.tsx
- packages/components/src/app/BaseApp.tsx
- packages/components/src/components/eventsCookieConsent/EventsCookieConsent.tsx
- packages/components/src/components/mapBox/MapBox.tsx
- packages/components/src/components/matomoWrapper/MatomoWrapper.tsx
- packages/components/src/cookieConfigurationProvider/CookieConfigurationContext.tsx
- packages/components/src/cookieConfigurationProvider/CookieConfigurationProvider.tsx
- packages/components/src/cookieConfigurationProvider/index.ts
- packages/components/src/cookieConfigurationProvider/useCookieConfigurationContext.tsx
now cookie consents given to tapahtumat.hel.fi, harrastukset.hel.fi and
liikunta.hel.fi should not be removed when navigating to www.hel.fi
closes LIIKUNTA-555
**[LIIKUNTA-555](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-555)**
[LIIKUNTA-555]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-555 | feat(cookies): set cookie domain to hostname i.e. <application>.hel.fi

- apps/sports-helsinki/src/domain/venue/venueCard/LargeVenueCard.tsx
- apps/sports-helsinki/src/domain/venue/venueHero/VenueHero.tsx
- apps/sports-helsinki/src/domain/venue/venueInfo/VenueInfo.tsx
- packages/components/src/components/domain/event/eventInfo/OrganizationInfo.tsx
- packages/components/src/components/eventName/EventName.tsx
- packages/components/src/components/helsinkiCityOwnedIcon/HelsinkiCityOwnedIcon.tsx
- packages/components/src/components/helsinkiCityOwnedIcon/helsinkiCityOwnedIcon.module.scss
- packages/components/src/components/index.ts
- packages/components/src/styles/helsinkiCityOwned.scss
refs LIIKUNTA-573
**[LIIKUNTA-573](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-573)**
[LIIKUNTA-573]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-573 | fix: keep Helsinki city owned icon on same row as the preceding text

- packages/components/src/types/generated/graphql.tsx
- proxies/events-graphql-federation/subgraphs/unified-search/unified-search.graphql
- proxies/events-graphql-federation/subgraphs/venues/venues.graphql
- proxies/events-graphql-federation/supergraph.graphql
Depends on:
- https://github.com/City-of-Helsinki/unified-search/pull/108 which depends on https://github.com/City-of-Helsinki/unified-search/pull/107
- https://github.com/City-of-Helsinki/unified-search/pull/109
update unified-search & venues subgraphs, compose supergraph and update
generated types after the following changes:
- https://github.com/City-of-Helsinki/unified-search/pull/108
- https://github.com/City-of-Helsinki/unified-search/pull/109
refs LIIKUNTA-27 (unified search PR #109)
refs LIIKUNTA-344 (unified search PR #109)
refs US-113 (unified search PR #108)
**[LIIKUNTA-27](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-27)**
**[LIIKUNTA-344](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-344)** …
> LIIKUNTA-27 | chore: update unified-search & venues subgraph, supergraph and types

- apps/sports-helsinki/src/domain/search/combinedSearch/SearchForm.tsx
- apps/sports-helsinki/src/domain/search/eventSearch/constants.tsx
target groups are now shown in the same order in the target groups'
dropdown as in https://liikunta.hel.fi/en/pages/target-groups when read
left-to-right top-to-bottom.
refs LIIKUNTA-344
**[LIIKUNTA-344](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-344)**
https://liikunta.hel.fi/fi/pages/kohderyhmat
https://liikunta.hel.fi/en/pages/target-groups
https://liikunta.hel.fi/sv/sidor/malgrupper
[LIIKUNTA-344]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-344 | fix: order target groups in dropdown similarly as in target groups' page

- apps/sports-helsinki/src/domain/search/venueList/VenueList.tsx
- apps/sports-helsinki/src/domain/unifiedSearch/useUnifiedSearchListQuery.ts
- apps/sports-helsinki/src/domain/venue/venueCard/LargeVenueCard.tsx
- packages/common-i18n/src/locales/en/common.json
- packages/common-i18n/src/locales/fi/common.json
- packages/common-i18n/src/locales/sv/common.json
- packages/components/src/components/domain/unifiedSearch/graphql/unifiedSearchList.query.ts
- packages/components/src/types/generated/graphql.tsx
show the currently chosen accessibility profile's shortcoming count in
the venues' search results
refs LIIKUNTA-566
**[LIIKUNTA-566](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-566)**
https://liikunta-pr521.dev.hel.ninja/
UI design based on [LIIKUNTA-27](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-27)'s this picture:
That's why the shortcoming count tag is on its own row and has "selected" attribute set to set the background color to dark grey.
[LIIKUNTA-566]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIIKUNTA-27]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
> LIIKUNTA-566 | feat(sports): show accessibility profile's shortcoming count in results

- packages/components/src/components/orderBySelect/EventsOrderBySelect.tsx
The outline handling was changed in
c7f5d7c60db4548c0d465f95e4a33a8f8e00502c which made the outline
disappear, add back the outline to the hobbies/events search's order by
select by removing the noOutline attribute
refs LIIKUNTA-568
[LIIKUNTA-568](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-568)
[LIIKUNTA-568]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-568 | fix: show outline in hobbies/events search's order by select

- apps/events-helsinki/src/domain/app/AppConfig.ts
- apps/hobbies-helsinki/src/domain/app/AppConfig.ts
- apps/sports-helsinki/src/domain/app/AppConfig.ts
- packages/components/src/app/BaseApp.tsx
- packages/components/src/app/useHdsStyleFix.tsx
- packages/components/src/components/askem/Askem.ts
- packages/components/src/components/askem/index.ts
- packages/components/src/components/askem/types.ts
- packages/components/src/components/askem/useAskemContext.tsx
- packages/components/src/components/footer/Footer.tsx
- packages/components/src/components/matomo/useMatomo.tsx
- packages/components/src/styles/askem.scss
- packages/components/src/types/types.ts
NOTE:
- There seems to be an underlying issue here that is not fully fixed
by this commit. This commit fixes the infinite looping to fetch
Askem's rns.js script and the unnecessary updating of AskemInstance
but  it's a tip of the iceberg so to speak, there's still something
being rerendered underneath. So, more work is needed to fix the
underlying issue.
parts:
- don't render AskemProvider and AskemFeedbackContainer on server-side
- don't update used AskemInstance except when it really changes, use
deep equality to compare
also:
- add more fields and documentation to Askem's data using
https://docs.reactandshare.com/
- pass all the Askem fields to window.rnsData
- fix AskemContext and AskemProvider default import renaming typos
refs HCRC-106
HCRC-106 …
> HCRC-109 | fix(askem): fix Askem looping to fetch rns.js on article pages

- packages/common-i18n/src/locales/en/appSports.json
refs LIIKUNTA-590
[LIIKUNTA-590](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-590)
[LIIKUNTA-590]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-590 | feat(sports): set english app name to "Sports and recreation"

- packages/components/src/components/navigation/Navigation.tsx
The problem was that router.query had no query parameters, even if the
current URL did when serving server-side pages. Using
window.location.search if it is available and router.query only as a
fallback fixes this.
refs LIIKUNTA-597
[LIIKUNTA-597](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-597)
Started with Finnish search:
- https://liikunta-pr574.dev.hel.ninja/fi/search?accessibilityProfile=wheelchair&searchType=Venue&sportsCategories=skiing&text=hiihto&venueOrderBy=wheelchair
- Changed to Swedish using "Svenska" text in header
- Got redirected to https://liikunta-pr574.dev.hel.ninja/sv/sok?accessibilityProfile=wheelchair&searchType=Venue&sportsCategories=skiing&text=hiihto&venueOrderBy=wheelchair
- Changed back to Finnish using "Suomi" text in header
- Got redirected …
> LIIKUNTA-597 | fix(navigation): fix retaining URL search parameters on language change

- packages/components/src/components/navigation/Navigation.tsx
fix bug that was introduced in 58ee85254bfe54a36b94de68d0a4039d98ef21bc
refs LIIKUNTA-597
[LIIKUNTA-597](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-597)
[LIIKUNTA-597]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-597 | fix(navigation): fix replacing [eventId] in URL when changing languages

- apps/events-helsinki/config/jest/TestProviders.tsx
- apps/events-helsinki/src/hooks/useEventsRHHCConfig.tsx
- apps/events-helsinki/src/pages/articles/[...slug].tsx
- apps/events-helsinki/src/pages/articles/index.tsx
- apps/hobbies-helsinki/config/jest/TestProviders.tsx
- apps/hobbies-helsinki/src/hooks/useHobbiesRHHCConfig.tsx
- apps/hobbies-helsinki/src/pages/articles/[...slug].tsx
- apps/hobbies-helsinki/src/pages/articles/index.tsx
- apps/sports-helsinki/config/jest/TestProviders.tsx
- apps/sports-helsinki/src/hooks/useSportsRHHCConfig.tsx
- apps/sports-helsinki/src/pages/articles/[...slug].tsx
- apps/sports-helsinki/src/pages/articles/index.tsx
- apps/sports-helsinki/src/pages/search/map.tsx
- packages/components/config/tests/app-test-providers.tsx
- packages/components/src/components/domain/event/useEventCards.tsx
- packages/components/src/utils/__tests__/getLanguageCode.test.ts
- packages/components/src/utils/__tests__/getLanguageCodeFilter.test.ts
- packages/components/src/utils/getLanguageCode.ts
- packages/components/src/utils/getLanguageCodeFilter.ts
- packages/components/src/utils/index.ts
Type unsafety in some parts of the codebase was noticed when code reviewing PR #605.
fix most of the underlying type problems (apolloClient's type is still
handled without type safety, add FIXME for that):
- related to react-helsinki-headless-cms Config type
- add missing fields to returned field named `copy`
- handle `currentLanguageCode` field type safely
- fix incorrect parameter and return type of
`utils.getEventCardProps`
- fix incorrect parameter type of `utils.getRoutedInternalHref`
refs HH-189
[HH-189](https://helsinkisolutionoffice.atlassian.net/browse/HH-189)
[HH-189]: https://helsinkisolutionoffice.atlassian.net/browse/HH-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HH-189 | fix(types): remove "as unknown as" type unsafe casts

- packages/components/src/utils/resilientTranslation/getResilientTranslation.ts
refs LIIKUNTA-606
[LIIKUNTA-606](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-606)
[LIIKUNTA-606]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-606 | fix: unknown error page's link text translations (fi & sv were swapped)

- packages/components/package.json
- yarn.lock
RHHC v1.0.0-alpha255 already uses hds-design-tokens v3.5.0,
so it's better to use the same version here also if there is no
particular reason for using v3.3.0.
refs LIIKUNTA-614 (upgraded hds-react to v3.5.0)
[LIIKUNTA-614](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-614)
[LIIKUNTA-614]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: upgrade hds-design-tokens to v3.5.0

- apps/sports-helsinki/src/styles/globals.scss
refs LIIKUNTA-620
[LIIKUNTA-620](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-620)
[LIIKUNTA-620]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-620 | fix: remove useless page margin

- apps/events-helsinki/src/styles/globals.scss
- apps/hobbies-helsinki/src/styles/globals.scss
- apps/sports-helsinki/src/styles/globals.scss
- packages/components/src/styles/globals.scss
refs LIIKUNTA-620 ("margin: 0" wasn't enough -> "margin: 0 !important")
[LIIKUNTA-620](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-620)
Tested locally using "yarn dev" & "yarn build && yarn start" using sports-helsinki and both worked.
[LIIKUNTA-620]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-620 | fix: remove page margin using !important in all globals.scss files

- packages/components/src/components/domain/event/eventInfo/__tests__/EventInfo.test.tsx
- packages/components/src/components/domain/event/eventInfo/utils/EventInfo.mocks.ts
- packages/components/src/components/shareLinks/__tests__/FacebookShareLink.test.tsx
- packages/components/src/components/shareLinks/__tests__/LinkedInShareLink.test.tsx
- packages/components/src/components/shareLinks/__tests__/ShareLinks.test.tsx
- packages/components/src/components/shareLinks/__tests__/TwitterShareLink.test.tsx
- packages/components/src/types/types.ts
```
yarn
cd packages/components
yarn test
```
->
```
Test Suites: 1 skipped, 64 passed, 64 of 65 total
Tests:       24 skipped, 226 passed, 250 total
Snapshots:   28 passed, 28 total
Time:        34.789 s, estimated 36 s
Ran all test suites.
```
refs LIIKUNTA-651
[LIIKUNTA-651](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-651)
[LIIKUNTA-651]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIIKUNTA-651 | fix(test): fix packages/components tests, remove unnecessary type casts

- packages/components/src/components/domain/unifiedSearch/unifiedSearchConstants.ts
**fix: remove dog beaches from swimming ontology**
refs LIIKUNTA-675
**[LIIKUNTA-675](https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-675)**
[LIIKUNTA-675]: https://helsinkisolutionoffice.atlassian.net/browse/LIIKUNTA-675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove dog beaches from swimming ontology

- apps/events-helsinki/package.json
- apps/hobbies-helsinki/package.json
- apps/sports-helsinki/package.json
- apps/sports-helsinki/redirectCampaignRoutes.config.js
- apps/sports-helsinki/src/edge-runtime-compatible/README.md
- apps/sports-helsinki/src/edge-runtime-compatible/__tests__/isObject.test.tsx
- apps/sports-helsinki/src/edge-runtime-compatible/__tests__/isStringOrNull.test.tsx
- apps/sports-helsinki/src/edge-runtime-compatible/__tests__/isValidRedirectAddress.tsx
- apps/sports-helsinki/src/edge-runtime-compatible/__tests__/parseRedirects.test.tsx
- apps/sports-helsinki/src/edge-runtime-compatible/constants.ts
- apps/sports-helsinki/src/edge-runtime-compatible/isValidRedirectAddress.ts
- apps/sports-helsinki/src/edge-runtime-compatible/parseRedirects.ts
- apps/sports-helsinki/src/edge-runtime-compatible/queryRedirects.ts
- apps/sports-helsinki/src/edge-runtime-compatible/redirectsCache.ts
- apps/sports-helsinki/src/edge-runtime-compatible/stripLocale.ts
- apps/sports-helsinki/src/edge-runtime-compatible/typeguards.ts
- apps/sports-helsinki/src/edge-runtime-compatible/types.ts
- apps/sports-helsinki/src/middleware.ts
- packages/components/package.json
- packages/components/src/components/domain/event/queryUtils.ts
- packages/components/src/types/generated/graphql.tsx
- packages/components/src/types/types.ts
- packages/components/src/utils/headless-cms/service.tsx
- packages/graphql-proxy-server/package.json
- proxies/venue-graphql-proxy/src/schema/paginationSchema.ts
- proxies/venue-graphql-proxy/src/types/types.ts
- yarn.lock
The redirects are fetched periodically from CMS's GraphQL endpoint for
siteSettings.redirects. The redirects' cache is in-memory and per pod,
and the cache is refreshed from CMS by default between 6–9 minutes
(i.e. 5–10min interval but a bit tighter and under 10min).
Redirects' cache updating interval can be configured using environment
variables:
- MIN_REDIRECTS_UPDATE_INTERVAL_MS (defaults to 6min in milliseconds)
- MAX_REDIRECTS_UPDATE_INTERVAL_MS (defaults to 9min in millseconds)
Also update generated GraphQL schemas i.e. ran:
```bash
cd apps/sports-helsinki/
yarn generate:graphql
cp ./src/components/domain/graphql/generated/graphql.tsx \
../../packages/components/src/types/generated/
cd ../../
npx prettier ./packages/components/src/types/generated/graphql.tsx -w
rm -fr …
```
> LIIKUNTA-655: Add dynamic CMS configured redirect to Liikunta only
